export const ATTENDANCE_REQUEST='ATTENDANCE_REQUEST'
export const ATTENDANCE_SUCCESS='ATTENDANCE_SUCCESS'
export const ATTENDANCE_FAIL='ATTENDANCE_FAIL'


export const TODAY_ATTENDANCE_REQUEST='TODAY_ATTENDANCE_REQUEST'
export const TODAY_ATTENDANCE_SUCCESS='TODAY_ATTENDANCE_SUCCESS'
export const TODAY_ATTENDANCE_FAIL='TODAY_ATTENDANCE_FAIL'

export const LEAVE_SUCCESS='LEAVE_SUCCESS'
export const LEAVE_FAIL='LEAVE_FAIL'
export const LEAVE_REQUEST='LEAVE_REQUEST'