# Generated by Django 4.1 on 2022-09-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userVerify',
            new_name='verifying',
        ),
        migrations.DeleteModel(
            name='demo',
        ),
    ]
